#!/usr/bin/env python3
"""Generate EXP_NEG_LUT for X-Market on Sui (Move)."""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

SCALE = 2**32
STEPS = 801
PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUT_MOVE = PROJECT_ROOT / "sources" / "math" / "exp_neg_lut.move"
OUT_JSON = Path(__file__).resolve().parent.parent / "exp_neg_lut.json"


def write_move_lut(lut: list[int]) -> None:
    OUT_MOVE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// @generated by math-spec/scripts/gen_exp_neg_lut.py — do not edit",
        "module x_market::math_exp_neg_lut;",
        "",
        "/// e^(-lambda) LUT: index = lambda * 100, lambda in [0, 8.00]",
        "public fun exp_neg_lut(lambda_fp: u128): u128 {",
        "    let idx = exp_neg_index(lambda_fp);",
        "    *vector::borrow(&exp_neg_table(), idx)",
        "}",
        "",
        "public fun exp_neg_index(lambda_fp: u128): u64 {",
        "    let scale = 4294967296u128;",
        "    let max_idx = 800u64;",
        "    let raw = (lambda_fp * 100) / scale;",
        "    if (raw > (max_idx as u128)) max_idx else (raw as u64)",
        "}",
        "",
        "public fun exp_neg_table(): vector<u128> {",
        "    vector[",
    ]
    for i in range(0, STEPS, 4):
        chunk = ", ".join(str(lut[j]) for j in range(i, min(i + 4, STEPS)))
        lines.append(f"        {chunk},")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    OUT_MOVE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    lut = [round(math.exp(-i / 100.0) * SCALE) for i in range(STEPS)]
    write_move_lut(lut)
    OUT_JSON.write_text(
        json.dumps({"scale": SCALE, "steps": STEPS, "values_fp": lut}, indent=2),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_MOVE}", file=sys.stderr)
    print(f"Wrote {OUT_JSON}", file=sys.stderr)


if __name__ == "__main__":
    main()
