// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_32_b58`, `decode_nonce`, `derive_shared_secret`, `encrypt_payload`

String phantomGenerateDappEncryptionKeypair() =>
    RustLib.instance.api.crateApiPhantomPhantomGenerateDappEncryptionKeypair();

String phantomEncryptSignTransactionPayload({
  required String dappSecretKeyB58,
  required String phantomWalletPubkeyB58,
  required String session,
  required String transactionBytesBase64,
}) => RustLib.instance.api.crateApiPhantomPhantomEncryptSignTransactionPayload(
  dappSecretKeyB58: dappSecretKeyB58,
  phantomWalletPubkeyB58: phantomWalletPubkeyB58,
  session: session,
  transactionBytesBase64: transactionBytesBase64,
);

String base58ToBase64({required String inputB58}) =>
    RustLib.instance.api.crateApiPhantomBase58ToBase64(inputB58: inputB58);

String phantomEncryptSignMessagePayload({
  required String dappSecretKeyB58,
  required String phantomWalletPubkeyB58,
  required String session,
  required String messageUtf8,
}) => RustLib.instance.api.crateApiPhantomPhantomEncryptSignMessagePayload(
  dappSecretKeyB58: dappSecretKeyB58,
  phantomWalletPubkeyB58: phantomWalletPubkeyB58,
  session: session,
  messageUtf8: messageUtf8,
);

String phantomDecryptPayload({
  required String dappSecretKeyB58,
  required String phantomWalletPubkeyB58,
  required String nonceB58,
  required String dataB58,
}) => RustLib.instance.api.crateApiPhantomPhantomDecryptPayload(
  dappSecretKeyB58: dappSecretKeyB58,
  phantomWalletPubkeyB58: phantomWalletPubkeyB58,
  nonceB58: nonceB58,
  dataB58: dataB58,
);

String phantomPublicKeyToSuiAddress({required String pubkeyB58}) => RustLib
    .instance
    .api
    .crateApiPhantomPhantomPublicKeyToSuiAddress(pubkeyB58: pubkeyB58);

bool phantomVerifySignMessage({
  required String pubkeyB58,
  required String messageUtf8,
  required String signatureB58,
}) => RustLib.instance.api.crateApiPhantomPhantomVerifySignMessage(
  pubkeyB58: pubkeyB58,
  messageUtf8: messageUtf8,
  signatureB58: signatureB58,
);
