// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// GENERATED by bootstrap-mobile-env.ps1 — DO NOT EDIT
// Network: testnet · Package: 0x1a175ee8ba5ae34cedc2f09e5cde8da1bff2fd11cfda7ade4fc369e84e5602a0

class SuiConfig {
  static const String network = 'testnet';
  static const String rpcUrl = 'https://fullnode.testnet.sui.io:443';

  static const String packageId = '0x1a175ee8ba5ae34cedc2f09e5cde8da1bff2fd11cfda7ade4fc369e84e5602a0';
  static const String usdcCoinType =
      '0xa1ec7fc00a6f40db9693ad1415d0c193ad3906494428cf252621037bd7117e29::usdc::USDC';
  static const String suiClockId = '0x6';

  static const String prophetRegistryId = '0x51b2bc4fa6178689c28efc47237849ac9e730ff540a135e0f275ad6e7948b722';
  static const String oracleConfigId = '0xd9b613093f602967a23403fa961b892ede5d477b5404139ea9746e3bec6bdf58';
  static const String gasStationUrl = 'http://localhost:8787';
  static const String indexerUrl = 'http://localhost:8800';
  static const String pricingEngineUrl = 'http://localhost:8801';
  static const String ipfsGatewayUrl = 'https://w3s.link';

  static const List<SeedPool> seedPools = [
    SeedPool(id: '0xd06cc96ccceb7f974821613216388f1a63bee0c94af76946c7d405e62582bdfa', label: 'Total goals · Poisson', kind: 'poisson'),
    SeedPool(id: '0xe600bb7269c52205af6c4c10e0eac1ae57aac409ddecb3223297d47a587563bf', label: 'Win / Draw / Loss · Dirichlet', kind: 'dirichlet'),
    SeedPool(id: '0x9b33a323620edfd2fca3328c59b34d99b4250d77f8322677faed7b91bcd60cdc', label: 'CPI range · Normal', kind: 'normal'),
    SeedPool(id: '0x4ef004ec7e21ce04c5a085ee45ac30309133b90f46e950a6a3dec3354c1018f6', label: 'Vote share · Beta', kind: 'beta'),
  ];
}

class SeedPool {
  const SeedPool({required this.id, required this.label, required this.kind});

  final String id;
  final String label;
  final String kind;
}