// GENERATED by bootstrap-mobile-env.ps1 鈥?DO NOT EDIT
// Network: testnet 路 Package: 0x2e368e00532771eedd2df288bd61b0cb2324471b9fc6e14160a7f3079310ae6e

class SuiConfig {
  static const String network = 'testnet';
  static const String rpcUrl = 'https://fullnode.testnet.sui.io:443';

  static const String packageId = '0x2e368e00532771eedd2df288bd61b0cb2324471b9fc6e14160a7f3079310ae6e';
  static const String usdcCoinType = '0xb2af3cb8af06e9754f442680ff2d191b8cc3a16ee661197534e6dc435e1eabce::usdc::USDC';
  static const String faucetPackageId = '0x2e368e00532771eedd2df288bd61b0cb2324471b9fc6e14160a7f3079310ae6e';
  static const String suiClockId = '0x6';

  static const String prophetRegistryId = '0xfa8359d6e1693542ef315eeda6a5c6c659dc819683a7bf86ac3391d1c4f63f38';
  static const String oracleConfigId = '0x1ad185d06bcbb53a98c5a834516da7a28c748f32079faa8ff310a35d04f663d8';
  static const String gasStationUrl = 'http://localhost:8787';
  static const String indexerUrl = 'http://localhost:8800';

  static const List<SeedPool> seedPools = [
    SeedPool(id: '0xb5d1a85213d6757d1cb386e8b719b524162a117018e6f5b8f0101f4dcc532b5f', label: '瓒崇悆鎬昏繘鐞?路 Poisson', kind: 'poisson'),
    SeedPool(id: '0x89fb5ff5754fe5b2d32d071ce98ad778b62a48f738e0d7dd27a86b390eddaac5', label: '鑳滃钩璐?路 Dirichlet', kind: 'dirichlet'),
    SeedPool(id: '0xa43716a746c01d6039cd7b9e6a77562f17a8730dc72c9363ddfde06859e4f834', label: 'CPI 鍖洪棿 路 Normal', kind: 'normal'),
  ];
}

class SeedPool {
  const SeedPool({required this.id, required this.label, required this.kind});

  final String id;
  final String label;
  final String kind;
}
