// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/phantom.dart';
import 'api/simple.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -824292851;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_x_market_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiPhantomBase58ToBase64({required String inputB58});

  String crateApiWalletDeriveSuiAddressFromPrivateKeyHex({
    required String privateKeyHex,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  String crateApiPhantomPhantomDecryptPayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String nonceB58,
    required String dataB58,
  });

  String crateApiPhantomPhantomEncryptSignMessagePayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String session,
    required String messageUtf8,
  });

  String crateApiPhantomPhantomEncryptSignTransactionPayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String session,
    required String transactionBytesBase64,
  });

  String crateApiPhantomPhantomGenerateDappEncryptionKeypair();

  String crateApiPhantomPhantomPublicKeyToSuiAddress({
    required String pubkeyB58,
  });

  bool crateApiPhantomPhantomVerifySignMessage({
    required String pubkeyB58,
    required String messageUtf8,
    required String signatureB58,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiPhantomBase58ToBase64({required String inputB58}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputB58, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhantomBase58ToBase64ConstMeta,
        argValues: [inputB58],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhantomBase58ToBase64ConstMeta =>
      const TaskConstMeta(
        debugName: "base58_to_base64",
        argNames: ["inputB58"],
      );

  @override
  String crateApiWalletDeriveSuiAddressFromPrivateKeyHex({
    required String privateKeyHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(privateKeyHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletDeriveSuiAddressFromPrivateKeyHexConstMeta,
        argValues: [privateKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletDeriveSuiAddressFromPrivateKeyHexConstMeta =>
      const TaskConstMeta(
        debugName: "derive_sui_address_from_private_key_hex",
        argNames: ["privateKeyHex"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String crateApiPhantomPhantomDecryptPayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String nonceB58,
    required String dataB58,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dappSecretKeyB58, serializer);
          sse_encode_String(phantomWalletPubkeyB58, serializer);
          sse_encode_String(nonceB58, serializer);
          sse_encode_String(dataB58, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhantomPhantomDecryptPayloadConstMeta,
        argValues: [
          dappSecretKeyB58,
          phantomWalletPubkeyB58,
          nonceB58,
          dataB58,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhantomPhantomDecryptPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_decrypt_payload",
        argNames: [
          "dappSecretKeyB58",
          "phantomWalletPubkeyB58",
          "nonceB58",
          "dataB58",
        ],
      );

  @override
  String crateApiPhantomPhantomEncryptSignMessagePayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String session,
    required String messageUtf8,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dappSecretKeyB58, serializer);
          sse_encode_String(phantomWalletPubkeyB58, serializer);
          sse_encode_String(session, serializer);
          sse_encode_String(messageUtf8, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhantomPhantomEncryptSignMessagePayloadConstMeta,
        argValues: [
          dappSecretKeyB58,
          phantomWalletPubkeyB58,
          session,
          messageUtf8,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhantomPhantomEncryptSignMessagePayloadConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_encrypt_sign_message_payload",
        argNames: [
          "dappSecretKeyB58",
          "phantomWalletPubkeyB58",
          "session",
          "messageUtf8",
        ],
      );

  @override
  String crateApiPhantomPhantomEncryptSignTransactionPayload({
    required String dappSecretKeyB58,
    required String phantomWalletPubkeyB58,
    required String session,
    required String transactionBytesBase64,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dappSecretKeyB58, serializer);
          sse_encode_String(phantomWalletPubkeyB58, serializer);
          sse_encode_String(session, serializer);
          sse_encode_String(transactionBytesBase64, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiPhantomPhantomEncryptSignTransactionPayloadConstMeta,
        argValues: [
          dappSecretKeyB58,
          phantomWalletPubkeyB58,
          session,
          transactionBytesBase64,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPhantomPhantomEncryptSignTransactionPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_encrypt_sign_transaction_payload",
        argNames: [
          "dappSecretKeyB58",
          "phantomWalletPubkeyB58",
          "session",
          "transactionBytesBase64",
        ],
      );

  @override
  String crateApiPhantomPhantomGenerateDappEncryptionKeypair() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiPhantomPhantomGenerateDappEncryptionKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPhantomPhantomGenerateDappEncryptionKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_generate_dapp_encryption_keypair",
        argNames: [],
      );

  @override
  String crateApiPhantomPhantomPublicKeyToSuiAddress({
    required String pubkeyB58,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pubkeyB58, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhantomPhantomPublicKeyToSuiAddressConstMeta,
        argValues: [pubkeyB58],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhantomPhantomPublicKeyToSuiAddressConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_public_key_to_sui_address",
        argNames: ["pubkeyB58"],
      );

  @override
  bool crateApiPhantomPhantomVerifySignMessage({
    required String pubkeyB58,
    required String messageUtf8,
    required String signatureB58,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pubkeyB58, serializer);
          sse_encode_String(messageUtf8, serializer);
          sse_encode_String(signatureB58, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhantomPhantomVerifySignMessageConstMeta,
        argValues: [pubkeyB58, messageUtf8, signatureB58],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhantomPhantomVerifySignMessageConstMeta =>
      const TaskConstMeta(
        debugName: "phantom_verify_sign_message",
        argNames: ["pubkeyB58", "messageUtf8", "signatureB58"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
