#!/usr/bin/env bash
# Copyright (c) 2026 zouyc zouyccq@gmail.com.
# All rights reserved.
#
# Licensed under the Business Source License 1.1 (BSL 1.1).
# You may not use this file except in compliance with the License.
#
# Change Date: 2031-01-01
# On the Change Date, or the fourth anniversary of the first publicly available
# distribution of the code under the BSL, whichever comes first, the code
# automatically becomes available under the Apache License 2.0.

# Shared helpers for production deploy (Ubuntu backend + Vercel frontend)
set -euo pipefail

_prod_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=testnet-common.sh
source "${_prod_script_dir}/testnet-common.sh"

FRONTEND_URL="${FRONTEND_URL:-}"
API_BASE_URL="${API_BASE_URL:-}"
API_ROUTING="${API_ROUTING:-path}" # path | direct | vercel-proxy
BACKEND_PROXY_HOST="${BACKEND_PROXY_HOST:-${XMARKET_BACKEND_PROXY_HOST:-}}"
DEPLOYER_PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY:-${XMARKET_DEPLOYER_PRIVATE_KEY:-}}"

strip_trailing_slash() {
  local url="${1%/}"
  echo "$url"
}

require_url() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "Missing required URL: ${name}" >&2
    exit 1
  fi
  if [[ ! "$value" =~ ^https?:// ]]; then
    echo "${name} must start with http:// or https:// (got: ${value})" >&2
    exit 1
  fi
}

service_public_url() {
  local service="$1"
  local base
  base="$(strip_trailing_slash "$API_BASE_URL")"
  case "$API_ROUTING" in
    direct)
      case "$service" in
        gas) echo "${base}:8787" ;;
        indexer) echo "${base}:8800" ;;
        pricing) echo "${base}:8801" ;;
        walrus) echo "${base}:8791" ;;
        *) echo "Unknown service: ${service}" >&2; return 1 ;;
      esac
      ;;
    path | *)
      case "$service" in
        gas) echo "${base}/gas" ;;
        indexer) echo "${base}/indexer" ;;
        pricing) echo "${base}/pricing" ;;
        walrus) echo "${base}/walrus" ;;
        *) echo "Unknown service: ${service}" >&2; return 1 ;;
      esac
      ;;
    vercel-proxy)
      case "$service" in
        gas) echo "/api/gas" ;;
        indexer) echo "/api/indexer" ;;
        pricing) echo "/api/pricing" ;;
        walrus) echo "/api/walrus" ;;
        *) echo "Unknown service: ${service}" >&2; return 1 ;;
      esac
      ;;
  esac
}

resolve_deployer_private_key() {
  if [[ -n "$DEPLOYER_PRIVATE_KEY" ]]; then
    echo "$DEPLOYER_PRIVATE_KEY"
    return 0
  fi
  if [[ -n "${XMARKET_DEPLOYER_PRIVATE_KEY:-}" ]]; then
    echo "$XMARKET_DEPLOYER_PRIVATE_KEY"
    return 0
  fi
  if [[ -n "${XMARKET_DEPLOYER_PRIVATE_KEY_FILE:-}" && -f "$XMARKET_DEPLOYER_PRIVATE_KEY_FILE" ]]; then
    tr -d '\r\n' <"$XMARKET_DEPLOYER_PRIVATE_KEY_FILE"
    return 0
  fi
  require_cmd sui
  local deployer active
  deployer="$(deploy_json_get deployer)"
  active="$(sui client active-address | tr -d '[:space:]')"
  if [[ "$active" != "$deployer" ]]; then
    echo "WARN: Active address ${active} != deployer ${deployer}" >&2
  fi
  sui keytool export --key-identity "$active" --json | python3 -c "import sys,json; print(json.load(sys.stdin)['exportedPrivateKey'])"
}

deploy_json_optional() {
  local path="$1"
  python3 - "$DEPLOY_JSON" "$path" <<'PY'
import json, sys
path = sys.argv[2].split(".")
with open(sys.argv[1], encoding="utf-8") as f:
    d = json.load(f)
for p in path:
    if p not in d:
        sys.exit(0)
    d = d[p]
print(d)
PY
}

write_vercel_env_file() {
  local out="${1:-deploy/vercel.env.generated}"
  mkdir -p "$(dirname "$out")"

  local network package_id global_config admin_cap
  local pool_poisson pool_dirichlet pool_normal
  local oracle_config oracle_arbitrator prophet_registry usdc_type
  local gas_url indexer_url pricing_url

  network="$(deploy_json_get network)"
  package_id="$(deploy_json_get packageId)"
  global_config="$(deploy_json_get globalConfig)"
  pool_poisson="$(deploy_json_get seedMarkets.poisson_goals.poolId)"
  pool_dirichlet="$(deploy_json_get seedMarkets.dirichlet_wdl.poolId)"
  pool_normal="$(deploy_json_get seedMarkets.normal_cpi.poolId)"
  oracle_config="$(deploy_json_get oracle.oracleConfigId)"
  oracle_arbitrator="$(deploy_json_optional oracle.oracleArbitratorId)"
  prophet_registry="$(deploy_json_get prophet.registryId)"
  usdc_type="$(deploy_json_optional usdc.coinType)"
  admin_cap="$(deploy_json_optional adminCap)"

  gas_url="$(service_public_url gas)"
  indexer_url="$(service_public_url indexer)"
  pricing_url="$(service_public_url pricing)"

  cat >"$out" <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
NEXT_PUBLIC_PACKAGE_ID=${package_id}
NEXT_PUBLIC_SUI_NETWORK=${network}
NEXT_PUBLIC_POOL_POISSON=${pool_poisson}
NEXT_PUBLIC_POOL_DIRICHLET=${pool_dirichlet}
NEXT_PUBLIC_POOL_NORMAL=${pool_normal}
NEXT_PUBLIC_SUI_CLOCK=0x6
NEXT_PUBLIC_GLOBAL_CONFIG=${global_config}
NEXT_PUBLIC_ORACLE_CONFIG_ID=${oracle_config}
NEXT_PUBLIC_PROPHET_REGISTRY_ID=${prophet_registry}
NEXT_PUBLIC_SEAL_THRESHOLD=1
NEXT_PUBLIC_GAS_STATION_URL=${gas_url}
NEXT_PUBLIC_INDEXER_URL=${indexer_url}
NEXT_PUBLIC_PRICING_ENGINE_URL=${pricing_url}
EOF

  if [[ -n "$oracle_arbitrator" ]]; then
    echo "NEXT_PUBLIC_ORACLE_ARBITRATOR_ID=${oracle_arbitrator}" >>"$out"
  fi
  if [[ -n "$usdc_type" ]]; then
    echo "NEXT_PUBLIC_USDC_COIN_TYPE=${usdc_type}" >>"$out"
  fi
  if [[ -n "$admin_cap" ]]; then
    echo "NEXT_PUBLIC_ADMIN_CAP=${admin_cap}" >>"$out"
  fi

  if [[ -n "$FRONTEND_URL" ]]; then
    cat >>"$out" <<EOF
# Vercel Edge GeoBlock (optional)
# GEO_BLOCK_ENABLED=true
# GEO_BLOCKED_COUNTRIES=US,CN
EOF
  fi

  echo "Wrote ${out}"
}

write_vercel_server_env_file() {
  local out="${1:-deploy/vercel.server.env.generated}"
  [[ "$API_ROUTING" == "vercel-proxy" ]] || return 0
  [[ -n "$BACKEND_PROXY_HOST" ]] || {
    echo "vercel-proxy requires BACKEND_PROXY_HOST (--backend-host)" >&2
    exit 1
  }

  mkdir -p "$(dirname "$out")"
  cat >"$out" <<EOF
# Auto-generated — server-only (NOT NEXT_PUBLIC). Vercel → backend IP proxy.
BACKEND_PROXY_HOST=${BACKEND_PROXY_HOST}
BACKEND_PROXY_SCHEME=http
EOF
  echo "Wrote ${out}"
}
