#!/usr/bin/env bash
# Copyright (c) 2026 zouyc zouyccq@gmail.com.
# All rights reserved.
#
# Licensed under the Business Source License 1.1 (BSL 1.1).
# You may not use this file except in compliance with the License.
#
# Change Date: 2031-01-01
# On the Change Date, or the fourth anniversary of the first publicly available
# distribution of the code under the BSL, whichever comes first, the code
# automatically becomes available under the Apache License 2.0.

# 生成生产环境链下服务 .env.local + Vercel 前端环境变量文件
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/production-common.sh
source "${SCRIPT_DIR}/lib/production-common.sh"

PROFILE="p2"
DRY_RUN_KEEPER=false
WRITE_VERCEL_ENV=true
RUNTIME="docker"
POSTGRES_MODE="docker"

usage() {
  cat <<EOF
Usage: $0 --frontend-url URL [OPTIONS]

Required:
  --frontend-url URL     Vercel 前端公网地址（CORS），如 https://x-market.vercel.app

API 地址（二选一）:
  --api-base-url URL     直连/Nginx 模式：API 网关，如 https://api.example.com
  --api-routing vercel-proxy --backend-host IP   Vercel 反向代理（仅公网 IP，无需域名）

Options:
  --profile PROFILE      p1 | p2 | full  (default: p2)
  --api-routing MODE     path | direct | vercel-proxy  (default: path)
  --backend-host IP      后端公网 IP（vercel-proxy 必填，仅 Vercel 服务端可见）
  --runtime MODE         docker | native  (default: docker)
  --postgres-mode MODE   docker | native | external  (default: docker, native 运行时)
  --deploy-json PATH     Chain config (default: deploy/testnet-v2.json)
  --dry-run-keeper       LP Guard Keeper 仅观测
  --skip-vercel-env      不生成 deploy/vercel.env.generated
  -h, --help             Show help

Secrets (production — prefer env over sui keytool):
  XMARKET_DEPLOYER_PRIVATE_KEY       Deployer 私钥（suiprivkey...）
  XMARKET_DEPLOYER_PRIVATE_KEY_FILE  私钥文件路径
  XMARKET_BACKEND_PROXY_HOST         等同 --backend-host
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --frontend-url)
      FRONTEND_URL="$2"
      shift 2
      ;;
    --api-base-url)
      API_BASE_URL="$2"
      shift 2
      ;;
    --api-routing)
      API_ROUTING="$2"
      shift 2
      ;;
    --backend-host)
      BACKEND_PROXY_HOST="$2"
      shift 2
      ;;
    --runtime)
      RUNTIME="$2"
      shift 2
      ;;
    --postgres-mode)
      POSTGRES_MODE="$2"
      shift 2
      ;;
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --deploy-json)
      DEPLOY_JSON="$2"
      shift 2
      ;;
    --dry-run-keeper)
      DRY_RUN_KEEPER=true
      shift
      ;;
    --skip-vercel-env)
      WRITE_VERCEL_ENV=false
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_url "FRONTEND_URL" "$FRONTEND_URL"

if [[ "$API_ROUTING" == "vercel-proxy" ]]; then
  BACKEND_PROXY_HOST="${BACKEND_PROXY_HOST:-}"
  [[ -n "$BACKEND_PROXY_HOST" ]] || {
    echo "vercel-proxy requires --backend-host or XMARKET_BACKEND_PROXY_HOST" >&2
    exit 1
  }
  API_BASE_URL="${API_BASE_URL:-$FRONTEND_URL}"
else
  require_url "API_BASE_URL" "$API_BASE_URL"
fi
[[ -f "$DEPLOY_JSON" ]] || { echo "Missing ${DEPLOY_JSON}" >&2; exit 1; }
require_cmd python3

case "$PROFILE" in
  p1 | p2 | full) ;;
  *)
    echo "Invalid profile: ${PROFILE}" >&2
    exit 1
    ;;
esac

FRONTEND_URL="$(strip_trailing_slash "$FRONTEND_URL")"
API_BASE_URL="$(strip_trailing_slash "$API_BASE_URL")"

priv_key="$(resolve_deployer_private_key)"
[[ -n "$priv_key" ]] || { echo "Failed to resolve deployer private key" >&2; exit 1; }

network="$(deploy_json_get network)"
package_id="$(deploy_json_get packageId)"
pool_poisson="$(deploy_json_get seedMarkets.poisson_goals.poolId)"
pool_dirichlet="$(deploy_json_get seedMarkets.dirichlet_wdl.poolId)"
pool_normal="$(deploy_json_get seedMarkets.normal_cpi.poolId)"
pool_ids="${pool_poisson},${pool_dirichlet},${pool_normal}"
prophet_registry="$(deploy_json_get prophet.registryId)"
oracle_config="$(deploy_json_get oracle.oracleConfigId)"
rpc_url="https://fullnode.${network}.sui.io:443"
if [[ "$network" == "mainnet" ]]; then
  rpc_url="https://fullnode.mainnet.sui.io:443"
fi

gas_public="$(service_public_url gas)"
indexer_public="$(service_public_url indexer)"
pricing_public="$(service_public_url pricing)"
walrus_public="$(service_public_url walrus)"

keeper_dry="false"
keeper_prod="true"
if [[ "$DRY_RUN_KEEPER" == "true" ]]; then
  keeper_dry="true"
  keeper_prod="false"
fi

mkdir -p services/gas-station services/lp-guard-keeper services/chain-monitor \
  services/oracle-relayer services/walrus-relay services/prophet-audit-keeper \
  services/indexer pricing-engine

cat >services/gas-station/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
SUI_RPC_URL_FALLBACK=
PACKAGE_ID=${package_id}
GAS_PAYER_PRIVATE_KEY=${priv_key}
HOST=0.0.0.0
PORT=8787
GAS_STATION_PRODUCTION=true
CORS_ORIGIN=${FRONTEND_URL}
SPONSOR_RATE_LIMIT_PER_MIN=30
GAS_MIN_BALANCE_MIST=500000000
GAS_BALANCE_CHECK_MS=300000
ALERT_WEBHOOK_URL=
EOF

cat >services/lp-guard-keeper/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
X_MARKET_PACKAGE_ID=${package_id}
LP_GUARD_KEEPER_SECRET_KEY=${priv_key}
LP_GUARD_POOL_IDS=${pool_ids}
LP_GUARD_POLL_MS=30000
LP_GUARD_WINDOW_SAMPLES=10
LP_GUARD_MAX_EFFECTIVE_FEE_BPS=800
LP_GUARD_MAX_FEE_MULTIPLIER_BPS=30000
LP_GUARD_MAX_SIGMA_VIRTUAL_TENTHS=20
LP_GUARD_MAX_CONCENTRATION_VIRTUAL=50
LP_GUARD_DECAY_FACTOR=0.85
LP_GUARD_UPDATE_THRESHOLD_BPS=200
LP_GUARD_DRY_RUN=${keeper_dry}
LP_GUARD_PRODUCTION=${keeper_prod}
LP_GUARD_HEALTH_PORT=8788
HOST=0.0.0.0
EOF

cat >services/chain-monitor/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
MONITOR_POOL_IDS=${pool_ids}
MONITOR_POLL_MS=60000
MONITOR_HEALTH_PORT=8789
MONITOR_LOOKBACK_SECS=86400
ALERT_WEBHOOK_URL=
GAS_STATION_HEALTH_URL=http://127.0.0.1:8787/health
KEEPER_HEALTH_URL=http://127.0.0.1:8788/health
HOST=0.0.0.0
EOF

cat >services/oracle-relayer/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
ORACLE_CONFIG_ID=${oracle_config}
ORACLE_POOL_IDS=${pool_ids}
ORACLE_RELAYER_POLL_MS=120000
ORACLE_RELAYER_HEALTH_PORT=8790
ORACLE_NULLIFY_HOURS=72
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
EOF

walrus_upstream="https://publisher.walrus-testnet.walrus.space"
if [[ "$network" == "mainnet" ]]; then
  walrus_upstream="https://publisher.walrus.space"
fi

cat >services/walrus-relay/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
WALRUS_UPSTREAM_PUBLISHER_URL=${walrus_upstream}
WALRUS_RELAY_PORT=8791
WALRUS_RELAY_API_KEY=
WALRUS_RELAY_MAX_BODY_BYTES=10485760
HOST=0.0.0.0
EOF

cat >services/prophet-audit-keeper/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
X_MARKET_PACKAGE_ID=${package_id}
PROPHET_REGISTRY_ID=${prophet_registry}
PROPHET_AUDIT_POOL_IDS=${pool_ids}
PROPHET_AUDIT_KEEPER_SECRET_KEY=${priv_key}
PROPHET_AUDIT_POLL_MS=120000
PROPHET_AUDIT_DRY_RUN=true
PROPHET_AUDIT_HEALTH_PORT=8792
INDEXER_URL=http://127.0.0.1:8800
IPFS_GATEWAY_URL=https://w3s.link
SEAL_THRESHOLD=1
HOST=0.0.0.0
EOF

if [[ "$PROFILE" == "p2" || "$PROFILE" == "full" ]]; then
  deploy_basename="$(basename "$DEPLOY_JSON")"
  pg_user="${XMARKET_PG_USER:-xmarket}"
  pg_pass="${XMARKET_PG_PASSWORD:-xmarket}"
  pg_db="${XMARKET_PG_DATABASE:-xmarket_indexer}"
  if [[ "$RUNTIME" == "docker" ]]; then
    indexer_db_url="postgresql://${pg_user}:${pg_pass}@postgres:5432/${pg_db}"
  elif [[ "$POSTGRES_MODE" == "external" ]]; then
    indexer_db_url="${XMARKET_INDEXER_DATABASE_URL:?postgres-mode=external requires XMARKET_INDEXER_DATABASE_URL}"
  else
    indexer_db_url="postgresql://${pg_user}:${pg_pass}@localhost:5432/${pg_db}"
  fi
  cat >services/indexer/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
SUI_NETWORK=${network}
SUI_RPC_URL=${rpc_url}
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
PROPHET_REGISTRY_ID=${prophet_registry}
ORACLE_CONFIG_ID=${oracle_config}
SEED_DEPLOY_JSON=../../deploy/${deploy_basename}
INDEXER_DATABASE_URL=${indexer_db_url}
INDEXER_API_PORT=8800
INDEXER_EVENT_POLL_MS=15000
INDEXER_SNAPSHOT_POLL_MS=60000
INDEXER_STATS_POLL_MS=120000
INDEXER_CORS_ORIGIN=${FRONTEND_URL}
HOST=0.0.0.0
EOF
fi

if [[ "$PROFILE" == "full" ]]; then
  cat >pricing-engine/.env.local <<EOF
# Auto-generated by bootstrap-production-env.sh — DO NOT COMMIT
PRICING_ENGINE_PORT=8801
PRICING_CORS_ORIGIN=${FRONTEND_URL}
HOST=0.0.0.0
EOF
fi

echo "Wrote production service env files (profile=${PROFILE})"
echo "  Gas Station public:  ${gas_public}"
echo "  Indexer public:      ${indexer_public}"
echo "  Pricing public:      ${pricing_public}"
echo "  Walrus public:       ${walrus_public}"
echo "  CORS origin:         ${FRONTEND_URL}"
if [[ "$API_ROUTING" == "vercel-proxy" ]]; then
  echo "  Vercel proxy:        /api/* → http://${BACKEND_PROXY_HOST}:{8787,8800,8801}"
fi

if [[ "$WRITE_VERCEL_ENV" == "true" ]]; then
  write_vercel_env_file "deploy/vercel.env.generated"
  write_vercel_server_env_file "deploy/vercel.server.env.generated"
fi
