#!/usr/bin/env bash
# 从 deploy/testnet-v2.json + 当前 sui 活跃地址生成链下服务 .env.local
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/testnet-common.sh
source "${SCRIPT_DIR}/lib/testnet-common.sh"

DRY_RUN_KEEPER=false
CORS_ORIGIN="http://localhost:3000"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deploy-json)
      DEPLOY_JSON="$2"
      shift 2
      ;;
    --dry-run-keeper)
      DRY_RUN_KEEPER=true
      shift
      ;;
    --cors-origin)
      CORS_ORIGIN="$2"
      shift 2
      ;;
    -h | --help)
      echo "Usage: $0 [--deploy-json deploy/testnet-v2.json] [--dry-run-keeper] [--cors-origin URL]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

[[ -f "$DEPLOY_JSON" ]] || { echo "Missing ${DEPLOY_JSON}" >&2; exit 1; }
require_cmd sui
require_cmd python3

deployer="$(deploy_json_get deployer)"
active="$(sui client active-address | tr -d '[:space:]')"
if [[ "$active" != "$deployer" ]]; then
  echo "WARN: Active address ${active} != deployer ${deployer}. Keeper must hold pool authority." >&2
fi

priv_key="$(sui keytool export --key-identity "$active" --json | python3 -c "import sys,json; print(json.load(sys.stdin)['exportedPrivateKey'])")"
[[ -n "$priv_key" ]] || { echo "Failed to export key for ${active}" >&2; exit 1; }

package_id="$(deploy_json_get packageId)"
pool_poisson="$(deploy_json_get seedMarkets.poisson_goals.poolId)"
pool_dirichlet="$(deploy_json_get seedMarkets.dirichlet_wdl.poolId)"
pool_normal="$(deploy_json_get seedMarkets.normal_cpi.poolId)"
pool_ids="${pool_poisson},${pool_dirichlet},${pool_normal}"
prophet_registry="$(deploy_json_get prophet.registryId)"

oracle_config=""
if [[ -f app/.env.example ]]; then
  oracle_config="$(grep '^NEXT_PUBLIC_ORACLE_CONFIG_ID=' app/.env.example | head -1 | cut -d= -f2- || true)"
fi
oracle_config="${oracle_config:-$(deploy_json_get oracle.oracleConfigId)}"

keeper_dry="false"
keeper_prod="true"
if [[ "$DRY_RUN_KEEPER" == "true" ]]; then
  keeper_dry="true"
  keeper_prod="false"
fi

cat >services/gas-station/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
PACKAGE_ID=${package_id}
GAS_PAYER_PRIVATE_KEY=${priv_key}
HOST=0.0.0.0
PORT=8787
GAS_STATION_PRODUCTION=true
CORS_ORIGIN=${CORS_ORIGIN}
SPONSOR_RATE_LIMIT_PER_MIN=30
GAS_MIN_BALANCE_MIST=500000000
GAS_BALANCE_CHECK_MS=300000
ALERT_WEBHOOK_URL=
EOF

cat >services/lp-guard-keeper/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=${package_id}
LP_GUARD_KEEPER_SECRET_KEY=${priv_key}
LP_GUARD_POOL_IDS=${pool_ids}
LP_GUARD_POLL_MS=30000
LP_GUARD_WINDOW_SAMPLES=10
LP_GUARD_MAX_EFFECTIVE_FEE_BPS=800
LP_GUARD_MAX_FEE_MULTIPLIER_BPS=30000
LP_GUARD_MAX_SIGMA_VIRTUAL_TENTHS=20
LP_GUARD_MAX_CONCENTRATION_VIRTUAL=50
LP_GUARD_DECAY_FACTOR=0.85
LP_GUARD_UPDATE_THRESHOLD_BPS=200
LP_GUARD_DRY_RUN=${keeper_dry}
LP_GUARD_PRODUCTION=${keeper_prod}
LP_GUARD_HEALTH_PORT=8788
HOST=0.0.0.0
EOF

cat >services/chain-monitor/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
MONITOR_POOL_IDS=${pool_ids}
MONITOR_POLL_MS=60000
MONITOR_HEALTH_PORT=8789
MONITOR_LOOKBACK_SECS=86400
ALERT_WEBHOOK_URL=
GAS_STATION_HEALTH_URL=http://localhost:8787/health
KEEPER_HEALTH_URL=http://localhost:8788/health
HOST=0.0.0.0
EOF

cat >services/oracle-relayer/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
ORACLE_CONFIG_ID=${oracle_config}
ORACLE_POOL_IDS=${pool_ids}
ORACLE_RELAYER_POLL_MS=120000
ORACLE_RELAYER_HEALTH_PORT=8790
ORACLE_NULLIFY_HOURS=72
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
EOF

cat >services/walrus-relay/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
WALRUS_UPSTREAM_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
WALRUS_RELAY_PORT=8791
WALRUS_RELAY_API_KEY=
WALRUS_RELAY_MAX_BODY_BYTES=10485760
HOST=0.0.0.0
EOF

cat >services/prophet-audit-keeper/.env.local <<EOF
# Auto-generated by bootstrap-services-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=${package_id}
PROPHET_REGISTRY_ID=${prophet_registry}
PROPHET_AUDIT_POOL_IDS=${pool_ids}
PROPHET_AUDIT_KEEPER_SECRET_KEY=${priv_key}
PROPHET_AUDIT_POLL_MS=120000
PROPHET_AUDIT_DRY_RUN=true
PROPHET_AUDIT_HEALTH_PORT=8792
INDEXER_URL=http://localhost:8800
IPFS_GATEWAY_URL=https://w3s.link
SEAL_THRESHOLD=1
HOST=0.0.0.0
EOF

if [[ -f app/.env.example ]]; then
  [[ -f app/.env.local ]] || cp app/.env.example app/.env.local
  env_set_line app/.env.local "NEXT_PUBLIC_GAS_STATION_URL" "http://localhost:8787"
  env_set_line app/.env.local "NEXT_PUBLIC_INDEXER_URL" "http://localhost:8800"
fi

echo "Wrote services/gas-station/.env.local"
echo "Wrote services/lp-guard-keeper/.env.local"
echo "Wrote services/chain-monitor/.env.local"
echo "Wrote services/oracle-relayer/.env.local"
echo "Wrote services/walrus-relay/.env.local"
echo "Wrote services/prophet-audit-keeper/.env.local"
echo ""
echo "Keeper DRY_RUN=${keeper_dry}  PRODUCTION=${keeper_prod}"
echo "Pools: ${pool_ids}"
echo "Next: ./scripts/start-services-testnet.sh"
