#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/testnet-common.sh
source "${SCRIPT_DIR}/lib/testnet-common.sh"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deploy-json)
      DEPLOY_JSON="$2"
      shift 2
      ;;
    -h | --help)
      echo "Usage: $0 [--deploy-json deploy/testnet-v2.json]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

package_id="$(deploy_json_get packageId)"
prophet_registry="$(deploy_json_get prophet.registryId)"
oracle_config="$(deploy_json_get oracle.oracleConfigId)"

cat >services/indexer/.env.local <<EOF
# Auto-generated by bootstrap-indexer-env.sh — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=${package_id}
PROPHET_REGISTRY_ID=${prophet_registry}
ORACLE_CONFIG_ID=${oracle_config}
SEED_DEPLOY_JSON=../../deploy/testnet-v2.json
INDEXER_DATABASE_URL=postgresql://xmarket:xmarket@localhost:5432/xmarket_indexer
INDEXER_API_PORT=8800
INDEXER_EVENT_POLL_MS=15000
INDEXER_SNAPSHOT_POLL_MS=60000
INDEXER_STATS_POLL_MS=120000
INDEXER_CORS_ORIGIN=http://localhost:3000
HOST=0.0.0.0
EOF

echo "Wrote services/indexer/.env.local"

if [[ -f app/.env.local ]]; then
  env_set_line app/.env.local "NEXT_PUBLIC_INDEXER_URL" "http://localhost:8800"
  echo "Updated app/.env.local"
fi

echo "Next: docker compose -f docker-compose.indexer.yml up -d postgres"
echo "       ./scripts/start-indexer.sh"
