# Copyright (c) 2026 zouyc zouyccq@gmail.com.
# All rights reserved.
#
# Licensed under the Business Source License 1.1 (BSL 1.1).
# You may not use this file except in compliance with the License.
#
# Change Date: 2031-01-01
# On the Change Date, or the fourth anniversary of the first publicly available
# distribution of the code under the BSL, whichever comes first, the code
# automatically becomes available under the Apache License 2.0.

# 从 deploy/testnet-v2.json + 当前 sui 活跃地址生成链下服务 .env.local（不提交 git）
param(
  [string]$DeployJson = "deploy/testnet-v2.json",
  [switch]$DryRunKeeper,
  [string]$CorsOrigin = "http://localhost:3000"
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$deployPath = Join-Path $root $DeployJson
if (-not (Test-Path $deployPath)) {
  throw "Missing $DeployJson"
}
$deploy = Get-Content $deployPath -Raw | ConvertFrom-Json

$active = (sui client active-address).Trim()
if ($active -ne $deploy.deployer) {
  Write-Warning "Active address $active != deployer $($deploy.deployer). Keeper must hold pool authority."
}

$keyJson = sui keytool export --key-identity $active --json | ConvertFrom-Json
$privKey = $keyJson.exportedPrivateKey
if (-not $privKey) { throw "Failed to export key for $active" }

$poolIds = @(
  $deploy.seedMarkets.poisson_goals.poolId,
  $deploy.seedMarkets.dirichlet_wdl.poolId,
  $deploy.seedMarkets.normal_cpi.poolId
) -join ","

$oracleConfig = $deploy.oracle.oracleConfigId
$appExamplePath = "app/.env.example"
if (-not $oracleConfig) {
  if (Test-Path $appExamplePath) {
    $oracleLine = Get-Content $appExamplePath | Where-Object { $_ -match "^NEXT_PUBLIC_ORACLE_CONFIG_ID=" } | Select-Object -First 1
    if ($oracleLine) { $oracleConfig = ($oracleLine -split "=", 2)[1].Trim() }
  }
}
if (-not $oracleConfig) { $oracleConfig = "" }

$keeperDry = if ($DryRunKeeper) { "true" } else { "false" }
$keeperProd = if ($DryRunKeeper) { "false" } else { "true" }

$keeperEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=$($deploy.packageId)
LP_GUARD_KEEPER_SECRET_KEY=$privKey
LP_GUARD_POOL_IDS=$poolIds
LP_GUARD_POLL_MS=30000
LP_GUARD_WINDOW_SAMPLES=10
LP_GUARD_MAX_EFFECTIVE_FEE_BPS=800
LP_GUARD_MAX_FEE_MULTIPLIER_BPS=30000
LP_GUARD_MAX_SIGMA_VIRTUAL_TENTHS=20
LP_GUARD_MAX_CONCENTRATION_VIRTUAL=50
LP_GUARD_DECAY_FACTOR=0.85
LP_GUARD_UPDATE_THRESHOLD_BPS=200
LP_GUARD_DRY_RUN=$keeperDry
LP_GUARD_PRODUCTION=$keeperProd
LP_GUARD_HEALTH_PORT=8788
HOST=0.0.0.0
"@

$monitorEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
MONITOR_POOL_IDS=$poolIds
MONITOR_POLL_MS=60000
MONITOR_HEALTH_PORT=8789
MONITOR_LOOKBACK_SECS=86400
ALERT_WEBHOOK_URL=
KEEPER_HEALTH_URL=http://localhost:8788/health
HOST=0.0.0.0
"@

$relayerEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ORACLE_CONFIG_ID=$oracleConfig
ORACLE_POOL_IDS=$poolIds
ORACLE_RELAYER_POLL_MS=120000
ORACLE_RELAYER_HEALTH_PORT=8790
ORACLE_NULLIFY_HOURS=72
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@

$walrusEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
WALRUS_UPSTREAM_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
WALRUS_RELAY_PORT=8791
WALRUS_RELAY_API_KEY=
WALRUS_RELAY_MAX_BODY_BYTES=10485760
HOST=0.0.0.0
"@

$keeperPath = "services/lp-guard-keeper/.env.local"
$monitorPath = "services/chain-monitor/.env.local"
$relayerPath = "services/oracle-relayer/.env.local"
$walrusPath = "services/walrus-relay/.env.local"
$auditPath = "services/prophet-audit-keeper/.env.local"
$umaDvmPath = "services/uma-dvm-relayer/.env.local"
$zkProverPath = "services/brevis-zk-prover/.env.local"

$arbitratorId = $deploy.oracle.oracleArbitratorId
if (-not $arbitratorId -and (Test-Path "app/.env.local")) {
  $arbLine = Get-Content "app/.env.local" | Where-Object { $_ -match "^NEXT_PUBLIC_ORACLE_ARBITRATOR_ID=" } | Select-Object -First 1
  if ($arbLine) { $arbitratorId = ($arbLine -split "=", 2)[1].Trim() }
}

$umaDvmEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ORACLE_CONFIG_ID=$oracleConfig
ORACLE_ARBITRATOR_ID=$arbitratorId
UMA_DVM_RELAYER_SECRET_KEY=$privKey
UMA_DVM_POLL_MS=60000
UMA_DVM_HEALTH_PORT=8793
UMA_DVM_MODE=mock
UMA_DVM_MOCK_DELAY_MS=5000
UMA_DVM_MOCK_VERDICT=2
UMA_DVM_MOCK_RESOLVED_VALUE=0
UMA_API_URL=
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@

$auditEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=$($deploy.packageId)
PROPHET_REGISTRY_ID=$($deploy.prophet.registryId)
PROPHET_AUDIT_POOL_IDS=$poolIds
PROPHET_AUDIT_KEEPER_SECRET_KEY=$privKey
PROPHET_AUDIT_POLL_MS=120000
PROPHET_AUDIT_DRY_RUN=true
PROPHET_AUDIT_HEALTH_PORT=8792
INDEXER_URL=http://localhost:8800
IPFS_GATEWAY_URL=https://w3s.link
SEAL_THRESHOLD=1
HOST=0.0.0.0
"@
Set-Content -Path $keeperPath -Value $keeperEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $keeperPath -Value "`n"
Set-Content -Path $monitorPath -Value $monitorEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $monitorPath -Value "`n"
Set-Content -Path $relayerPath -Value $relayerEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $relayerPath -Value "`n"
Set-Content -Path $walrusPath -Value $walrusEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $walrusPath -Value "`n"
Set-Content -Path $auditPath -Value $auditEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $auditPath -Value "`n"
Set-Content -Path $umaDvmPath -Value $umaDvmEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $umaDvmPath -Value "`n"

$zkPolicyId = ""
if (Test-Path "app/.env.local") {
  $zkLine = Get-Content "app/.env.local" | Where-Object { $_ -match "^NEXT_PUBLIC_ZK_VERIFIER_POLICY_ID=" } | Select-Object -First 1
  if ($zkLine) { $zkPolicyId = ($zkLine -split "=", 2)[1].Trim() }
}

$zkProverEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ZK_PROVER_SECRET_KEY=$privKey
ZK_PROVER_POOL_IDS=$poolIds
ZK_VERIFIER_POLICY_ID=$zkPolicyId
ZK_PROVER_POLL_MS=120000
ZK_PROVER_HEALTH_PORT=8794
ZK_PROVER_MODE=mock
ZK_PROVER_DRY_RUN=true
ZK_PROVER_MOCK_DELAY_MS=3000
BREVIS_RPC_URL=
BREVIS_PARTNER_KEY=
BREVIS_SRC_CHAIN_ID=101
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@
Set-Content -Path $zkProverPath -Value $zkProverEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $zkProverPath -Value "`n"

# app/.env.local：从 deploy json 同步（保留 example 中未列出的可选项）
$appLocal = "app/.env.local"
$circleUsdc = $deploy.usdc.coinType
if (-not $circleUsdc) {
  $circleUsdc = "0xa1ec7fc00a6f40db9693ad1415d0c193ad3906494428cf252621037bd7117e29::usdc::USDC"
}
$appEnv = @"
# Auto-synced from $DeployJson
NEXT_PUBLIC_PACKAGE_ID=$($deploy.packageId)
NEXT_PUBLIC_SUI_NETWORK=testnet
NEXT_PUBLIC_POOL_POISSON=$($deploy.seedMarkets.poisson_goals.poolId)
NEXT_PUBLIC_POOL_DIRICHLET=$($deploy.seedMarkets.dirichlet_wdl.poolId)
NEXT_PUBLIC_POOL_NORMAL=$($deploy.seedMarkets.normal_cpi.poolId)
NEXT_PUBLIC_USDC_COIN_TYPE=$circleUsdc
NEXT_PUBLIC_SUI_CLOCK=0x6
NEXT_PUBLIC_GLOBAL_CONFIG=$($deploy.globalConfig)
NEXT_PUBLIC_ADMIN_CAP=$($deploy.adminCap)
NEXT_PUBLIC_ORACLE_CONFIG_ID=$($deploy.oracle.oracleConfigId)
NEXT_PUBLIC_ORACLE_ARBITRATOR_ID=$($deploy.oracle.oracleArbitratorId)
NEXT_PUBLIC_PROPHET_REGISTRY_ID=$($deploy.prophet.registryId)
NEXT_PUBLIC_SEAL_THRESHOLD=1
NEXT_PUBLIC_INDEXER_URL=http://localhost:8800
NEXT_PUBLIC_PRICING_ENGINE_URL=http://localhost:8801
"@
Set-Content -Path $appLocal -Value $appEnv.Trim() -Encoding UTF8

Write-Host "Wrote $keeperPath"
Write-Host "Wrote $monitorPath"
Write-Host "Wrote $relayerPath"
Write-Host "Wrote $walrusPath"
Write-Host "Wrote $auditPath"
Write-Host "Wrote $umaDvmPath"
Write-Host "Wrote $zkProverPath"
if (-not $zkPolicyId) {
  Write-Warning "ZK_VERIFIER_POLICY_ID empty — run .\scripts\init-zk-verifier-policy.ps1 then re-bootstrap"
}
if (Test-Path $appLocal) { Write-Host "Wrote $appLocal" }
Write-Host ""
Write-Host "Keeper DRY_RUN=$keeperDry  PRODUCTION=$keeperProd"
Write-Host "Pools: $poolIds"
Write-Host "Next: .\scripts\start-services-testnet.ps1"
