# P3.5 从 deploy JSON 生成 Flutter 网络配置（Testnet / Mainnet 模板）
param(
  [string]$DeployJson = "deploy/testnet-v2.json",
  [ValidateSet("testnet", "mainnet")]
  [string]$Network = "testnet"
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$deploy = Get-Content (Join-Path $root $DeployJson) -Raw | ConvertFrom-Json

$rpc = if ($Network -eq "mainnet") {
  "https://fullnode.mainnet.sui.io:443"
} else {
  "https://fullnode.testnet.sui.io:443"
}

$packageId = $deploy.packageId
$usdcPkg = if ($deploy.packageIdV1) { $deploy.packageIdV1 } else { $packageId }

$pools = @()
if ($deploy.seedMarkets) {
  $meta = @{
    poisson_goals = @{ label = "足球总进球 · Poisson"; kind = "poisson" }
    dirichlet_wdl = @{ label = "胜平负 · Dirichlet"; kind = "dirichlet" }
    normal_cpi    = @{ label = "CPI 区间 · Normal"; kind = "normal" }
    beta_vote     = @{ label = "得票率 · Beta"; kind = "beta" }
  }
  $order = @("poisson_goals", "dirichlet_wdl", "normal_cpi", "beta_vote")
  foreach ($key in $order) {
    if (-not $deploy.seedMarkets.$key) { continue }
    $s = $deploy.seedMarkets.$key
    $m = $meta[$key]
    if (-not $m) { continue }
    $pools += "    SeedPool(id: '$($s.poolId)', label: '$($m.label)', kind: '$($m.kind)'),"
  }
}
$poolBlock = ($pools -join "`n")

$dart = @"
// GENERATED by bootstrap-mobile-env.ps1 — DO NOT EDIT
// Network: $Network · Package: $packageId

class SuiConfig {
  static const String network = '$Network';
  static const String rpcUrl = '$rpc';

  static const String packageId = '$packageId';
  static const String usdcCoinType = '$usdcPkg::usdc::USDC';
  static const String faucetPackageId = '$packageId';
  static const String suiClockId = '0x6';

  static const String prophetRegistryId = '$($deploy.prophet.registryId)';
  static const String oracleConfigId = '$($deploy.oracle.oracleConfigId)';
  static const String gasStationUrl = 'http://localhost:8787';
  static const String indexerUrl = 'http://localhost:8800';
  static const String pricingEngineUrl = 'http://localhost:8801';
  static const String walrusPublisherUrl =
      'https://publisher.walrus-testnet.walrus.space';
  static const String walrusAggregatorUrl =
      'https://aggregator.walrus-testnet.walrus.space';
  static const int walrusEpochs = 2;

  static const List<SeedPool> seedPools = [
$poolBlock
  ];
}

class SeedPool {
  const SeedPool({required this.id, required this.label, required this.kind});

  final String id;
  final String label;
  final String kind;
}
"@

$out = Join-Path $root "mobile/x_market_flutter/lib/src/sui_config.dart"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($out, $dart.Trim(), $utf8NoBom)
Write-Host "Wrote $out ($Network)"
