# 从 deploy/testnet-v2.json + 当前 sui 活跃地址生成链下服务 .env.local（不提交 git）
param(
  [string]$DeployJson = "deploy/testnet-v2.json",
  [switch]$DryRunKeeper,
  [string]$CorsOrigin = "http://localhost:3000"
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$deployPath = Join-Path $root $DeployJson
if (-not (Test-Path $deployPath)) {
  throw "Missing $DeployJson"
}
$deploy = Get-Content $deployPath -Raw | ConvertFrom-Json

$active = (sui client active-address).Trim()
if ($active -ne $deploy.deployer) {
  Write-Warning "Active address $active != deployer $($deploy.deployer). Keeper must hold pool authority."
}

$keyJson = sui keytool export --key-identity $active --json | ConvertFrom-Json
$privKey = $keyJson.exportedPrivateKey
if (-not $privKey) { throw "Failed to export key for $active" }

$poolIds = @(
  $deploy.seedMarkets.poisson_goals.poolId,
  $deploy.seedMarkets.dirichlet_wdl.poolId,
  $deploy.seedMarkets.normal_cpi.poolId
) -join ","

$oracleConfig = $null
$appExamplePath = "app/.env.example"
if (Test-Path $appExamplePath) {
  $oracleLine = Get-Content $appExamplePath | Where-Object { $_ -match "^NEXT_PUBLIC_ORACLE_CONFIG_ID=" } | Select-Object -First 1
  if ($oracleLine) { $oracleConfig = ($oracleLine -split "=", 2)[1].Trim() }
}
if (-not $oracleConfig) { $oracleConfig = "" }

$gasEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
PACKAGE_ID=$($deploy.packageId)
GAS_PAYER_PRIVATE_KEY=$privKey
HOST=0.0.0.0
PORT=8787
GAS_STATION_PRODUCTION=true
CORS_ORIGIN=$CorsOrigin
SPONSOR_RATE_LIMIT_PER_MIN=30
GAS_MIN_BALANCE_MIST=500000000
GAS_BALANCE_CHECK_MS=300000
ALERT_WEBHOOK_URL=
"@

$keeperDry = if ($DryRunKeeper) { "true" } else { "false" }
$keeperProd = if ($DryRunKeeper) { "false" } else { "true" }

$keeperEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=$($deploy.packageId)
LP_GUARD_KEEPER_SECRET_KEY=$privKey
LP_GUARD_POOL_IDS=$poolIds
LP_GUARD_POLL_MS=30000
LP_GUARD_WINDOW_SAMPLES=10
LP_GUARD_MAX_EFFECTIVE_FEE_BPS=800
LP_GUARD_MAX_FEE_MULTIPLIER_BPS=30000
LP_GUARD_MAX_SIGMA_VIRTUAL_TENTHS=20
LP_GUARD_MAX_CONCENTRATION_VIRTUAL=50
LP_GUARD_DECAY_FACTOR=0.85
LP_GUARD_UPDATE_THRESHOLD_BPS=200
LP_GUARD_DRY_RUN=$keeperDry
LP_GUARD_PRODUCTION=$keeperProd
LP_GUARD_HEALTH_PORT=8788
HOST=0.0.0.0
"@

$monitorEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
MONITOR_POOL_IDS=$poolIds
MONITOR_POLL_MS=60000
MONITOR_HEALTH_PORT=8789
MONITOR_LOOKBACK_SECS=86400
ALERT_WEBHOOK_URL=
GAS_STATION_HEALTH_URL=http://localhost:8787/health
KEEPER_HEALTH_URL=http://localhost:8788/health
HOST=0.0.0.0
"@

$relayerEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ORACLE_CONFIG_ID=$oracleConfig
ORACLE_POOL_IDS=$poolIds
ORACLE_RELAYER_POLL_MS=120000
ORACLE_RELAYER_HEALTH_PORT=8790
ORACLE_NULLIFY_HOURS=72
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@

$walrusEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
WALRUS_UPSTREAM_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
WALRUS_RELAY_PORT=8791
WALRUS_RELAY_API_KEY=
WALRUS_RELAY_MAX_BODY_BYTES=10485760
HOST=0.0.0.0
"@

$gasPath = "services/gas-station/.env.local"
$keeperPath = "services/lp-guard-keeper/.env.local"
$monitorPath = "services/chain-monitor/.env.local"
$relayerPath = "services/oracle-relayer/.env.local"
$walrusPath = "services/walrus-relay/.env.local"
$auditPath = "services/prophet-audit-keeper/.env.local"
$umaDvmPath = "services/uma-dvm-relayer/.env.local"
$zkProverPath = "services/brevis-zk-prover/.env.local"

$arbitratorId = ""
if (Test-Path "app/.env.local") {
  $arbLine = Get-Content "app/.env.local" | Where-Object { $_ -match "^NEXT_PUBLIC_ORACLE_ARBITRATOR_ID=" } | Select-Object -First 1
  if ($arbLine) { $arbitratorId = ($arbLine -split "=", 2)[1].Trim() }
}

$umaDvmEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ORACLE_CONFIG_ID=$oracleConfig
ORACLE_ARBITRATOR_ID=$arbitratorId
UMA_DVM_RELAYER_SECRET_KEY=$privKey
UMA_DVM_POLL_MS=60000
UMA_DVM_HEALTH_PORT=8793
UMA_DVM_MODE=mock
UMA_DVM_MOCK_DELAY_MS=5000
UMA_DVM_MOCK_VERDICT=2
UMA_DVM_MOCK_RESOLVED_VALUE=0
UMA_API_URL=
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@

$auditEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
X_MARKET_PACKAGE_ID=$($deploy.packageId)
PROPHET_REGISTRY_ID=$($deploy.prophet.registryId)
PROPHET_AUDIT_POOL_IDS=$poolIds
PROPHET_AUDIT_KEEPER_SECRET_KEY=$privKey
PROPHET_AUDIT_POLL_MS=120000
PROPHET_AUDIT_DRY_RUN=true
PROPHET_AUDIT_HEALTH_PORT=8792
INDEXER_URL=http://localhost:8800
WALRUS_AGGREGATOR_URL=https://aggregator.walrus-testnet.walrus.space
SEAL_THRESHOLD=1
HOST=0.0.0.0
"@
Set-Content -Path $gasPath -Value $gasEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $gasPath -Value "`n"
Set-Content -Path $keeperPath -Value $keeperEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $keeperPath -Value "`n"
Set-Content -Path $monitorPath -Value $monitorEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $monitorPath -Value "`n"
Set-Content -Path $relayerPath -Value $relayerEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $relayerPath -Value "`n"
Set-Content -Path $walrusPath -Value $walrusEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $walrusPath -Value "`n"
Set-Content -Path $auditPath -Value $auditEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $auditPath -Value "`n"
Set-Content -Path $umaDvmPath -Value $umaDvmEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $umaDvmPath -Value "`n"

$zkPolicyId = ""
if (Test-Path "app/.env.local") {
  $zkLine = Get-Content "app/.env.local" | Where-Object { $_ -match "^NEXT_PUBLIC_ZK_VERIFIER_POLICY_ID=" } | Select-Object -First 1
  if ($zkLine) { $zkPolicyId = ($zkLine -split "=", 2)[1].Trim() }
}

$zkProverEnv = @"
# Auto-generated by bootstrap-services-env.ps1 — DO NOT COMMIT
SUI_NETWORK=testnet
SUI_RPC_URL=https://fullnode.testnet.sui.io:443
SUI_RPC_URL_FALLBACK=
X_MARKET_PACKAGE_ID=$($deploy.packageId)
ZK_PROVER_SECRET_KEY=$privKey
ZK_PROVER_POOL_IDS=$poolIds
ZK_VERIFIER_POLICY_ID=$zkPolicyId
ZK_PROVER_POLL_MS=120000
ZK_PROVER_HEALTH_PORT=8794
ZK_PROVER_MODE=mock
ZK_PROVER_DRY_RUN=true
ZK_PROVER_MOCK_DELAY_MS=3000
BREVIS_RPC_URL=
BREVIS_PARTNER_KEY=
BREVIS_SRC_CHAIN_ID=101
ALERT_WEBHOOK_URL=
HOST=0.0.0.0
"@
Set-Content -Path $zkProverPath -Value $zkProverEnv.Trim() -Encoding UTF8 -NoNewline
Add-Content -Path $zkProverPath -Value "`n"

# app/.env.local：基于 example + Gas Station URL
$appExample = "app/.env.example"
$appLocal = "app/.env.local"
if (Test-Path $appExample) {
  $appText = Get-Content $appExample -Raw
  if ($appText -notmatch "NEXT_PUBLIC_GAS_STATION_URL") {
    $appText += "`nNEXT_PUBLIC_GAS_STATION_URL=http://localhost:8787`n"
  } else {
    $appText = $appText -replace "NEXT_PUBLIC_GAS_STATION_URL=.*", "NEXT_PUBLIC_GAS_STATION_URL=http://localhost:8787"
  }
  if ($appText -notmatch "NEXT_PUBLIC_WALRUS_PUBLISHER_URL") {
    $appText += "NEXT_PUBLIC_WALRUS_PUBLISHER_URL=http://localhost:8791`n"
  } else {
    $appText = $appText -replace "NEXT_PUBLIC_WALRUS_PUBLISHER_URL=.*", "NEXT_PUBLIC_WALRUS_PUBLISHER_URL=http://localhost:8791"
  }
  Set-Content -Path $appLocal -Value $appText.TrimEnd() -Encoding UTF8
}

Write-Host "Wrote $gasPath"
Write-Host "Wrote $keeperPath"
Write-Host "Wrote $monitorPath"
Write-Host "Wrote $relayerPath"
Write-Host "Wrote $walrusPath"
Write-Host "Wrote $auditPath"
Write-Host "Wrote $umaDvmPath"
Write-Host "Wrote $zkProverPath"
if (-not $zkPolicyId) {
  Write-Warning "ZK_VERIFIER_POLICY_ID empty — run .\scripts\init-zk-verifier-policy.ps1 then re-bootstrap"
}
if (Test-Path $appLocal) { Write-Host "Wrote $appLocal" }
Write-Host ""
Write-Host "Keeper DRY_RUN=$keeperDry  PRODUCTION=$keeperProd"
Write-Host "Pools: $poolIds"
Write-Host "Next: .\scripts\start-services-testnet.ps1"
